### ISSUE TITLE
NSURLConnection+NM中hook_sendSynchronousRequest的方法, 当response和error是空时会崩溃

### ISSUE THREAD

**Issue by Ade0408** [frog78/NetworkMonitor#11]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/11570519/97961213-dc92e080-1ded-11eb-80d2-68a10e10e019.png">

如图所示, 因为这个是第三方SDK里发起的请求, 没办法详细看到它是怎么发起的请求, 其他的都没问题

**Comment by frog78** [comment]
经测试，当error为空时发生崩溃，已做相应处理，感谢反馈。
