### ISSUE TITLE
hook_dataTaskWithRequest:方法不执行

### ISSUE THREAD

**Issue by brave723** [frog78/NetworkMonitor#7]
用AF发送请求的时候，
- (NSURLSessionDataTask *)hook_dataTaskWithRequest:(NSURLRequest *)request completionHandler:(void (^)(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error))completionHandler {
    EELog(@"-------->start<--------");
}
该方法不执行，不知道什么原因

**Comment by frog78** [comment]
请提供详细信息。

**Comment by brave723** [comment]
就是跑你demo的时候，执行AFNetworking那个按钮，没有hook到网络请求

**Comment by frog78** [comment]
demo没有问题，sdk开关打开了没

**Comment by brave723** [comment]
![image](https://user-images.githubusercontent.com/1267034/83944046-4608c600-a833-11ea-96da-97aa509dc84a.png)
AF 的get方法，traceId一直为空

**Comment by frog78** [comment]
![907fd304-20a5-4704-8ab4-c9bc4360195c](https://user-images.githubusercontent.com/6000961/83962129-21612c80-a8cd-11ea-9ece-04c39f46a41a.png)
traceId不为空

**Comment by brave723** [comment]
我这边还是不行，793935562 能加我QQ？

**Comment by brave723** [comment]
> ![907fd304-20a5-4704-8ab4-c9bc4360195c](https://user-images.githubusercontent.com/6000961/83962129-21612c80-a8cd-11ea-9ece-04c39f46a41a.png)
> traceId不为空

我这边还是不行，465819560 能加我QQ？

**Comment by frog78** [comment]
@brave723  iOS 13上发现了你提出的，问题，现在已经修复。感谢反馈。

**Comment by frog78** [comment]
@brave723 已加你QQ.
