### ISSUE TITLE
dataTaskWithURL:或dataTaskWithURL:completionHandler:在iOS 13系统下问题

### ISSUE THREAD

**Issue by FantasticSkyBaby** [frog78/NetworkMonitor#8]
dataTaskWithURL:或dataTaskWithURL:completionHandler:在iOS 13系统下内部不再调用dataTaskWithRequest:系列方法，导致如上创建的请求监控失效

**Comment by frog78** [comment]
iOS13上dataTaskWithURL:/dataTaskWithRequest:不再调用dataTaskWithURL:completionHandler:导致该问题，已经修复。感谢反馈。

**Comment by FantasticSkyBaby** [comment]
[NMHooker hookInstance:@"NSURLSession" sel:@"dataTaskWithURL:" withClass:@"NSURLSession" andSel:@"hook_dataTaskWithURL:"];
[NMHooker hookInstance:@"NSURLSession" sel:@"dataTaskWithURL:completionHandler:" withClass:@"NSURLSession" andSel:@"hook_dataTaskWithURL:completionHandler:"];

这两个内部也不会走dataTaskWithRequest:completionHandler:了

**Comment by frog78** [comment]
> [NMHooker hookInstance:@"NSURLSession" sel:@"dataTaskWithURL:" withClass:@"NSURLSession" andSel:@"hook_dataTaskWithURL:"];
> [NMHooker hookInstance:@"NSURLSession" sel:@"dataTaskWithURL:completionHandler:" withClass:@"NSURLSession" andSel:@"hook_dataTaskWithURL:completionHandler:"];
> 
> 这两个内部也不会走dataTaskWithRequest:completionHandler:了

@FantasticSkyBaby 已修复。
